// <auto-generated />
using System;
using DiscogScrobblerMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscogScrobblerMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603072943_IntToLongDiscogsInstanceId")]
    partial class IntToLongDiscogsInstanceId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("ArtistRelease", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleasesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtistsId", "ReleasesId");

                    b.HasIndex("ReleasesId");

                    b.ToTable("ArtistRelease");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccountApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DiscogsCollectionValueFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsCollectionValueMax")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsCollectionValueMedian")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsCollectionValueMin")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsPersonalAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastFmSessionKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFmUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscogsArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DiscogsDetailsFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsProfile")
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFmArtistName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImageFilename")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalThumbnailFilename")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscogsArtistId")
                        .HasFilter("\"DiscogsArtistId\" IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.DiscogsReleaseImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscogsReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalImageFilename")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalThumbnailFilename")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscogsReleaseId")
                        .IsUnique();

                    b.ToTable("DiscogsReleaseImages");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.DiscogsReleaseToUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscogsFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DiscogsInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscogsReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscogsReleaseId");

                    b.HasIndex("UserId", "DiscogsInstanceId")
                        .IsUnique()
                        .HasFilter("[DiscogsInstanceId] IS NOT NULL");

                    b.HasIndex(new[] { "UserId", "DiscogsReleaseId" }, "IX_DiscogsReleaseToUsers_UserId_DiscogsReleaseId")
                        .IsUnique()
                        .HasFilter("[DiscogsInstanceId] IS NULL");

                    b.HasIndex(new[] { "UserId", "DiscogsReleaseId" }, "IX_DiscogsReleaseToUsers_UserId_DiscogsReleaseId_Plain");

                    b.ToTable("DiscogsReleaseToUsers");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DiscogsDetailsFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscogsLabelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscogsProfile")
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImageFilename")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalThumbnailFilename")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscogsLabelId")
                        .HasFilter("\"DiscogsLabelId\" IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommunityHaveCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommunityWantCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscogsMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscogsReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscogsReleaseId")
                        .IsUnique();

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.ReleaseGenre", b =>
                {
                    b.Property<int>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ReleaseGenres");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.ReleaseStyle", b =>
                {
                    b.Property<int>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StyleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseId", "StyleId");

                    b.HasIndex("StyleId");

                    b.ToTable("ReleaseStyles");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duration")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId", "Position");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("LabelRelease", b =>
                {
                    b.Property<int>("LabelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleasesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LabelsId", "ReleasesId");

                    b.HasIndex("ReleasesId");

                    b.ToTable("LabelRelease");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArtistRelease", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Release", null)
                        .WithMany()
                        .HasForeignKey("ReleasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.DiscogsReleaseImages", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Release", "Release")
                        .WithOne("Images")
                        .HasForeignKey("DiscogScrobblerMVC.Data.Entities.DiscogsReleaseImages", "DiscogsReleaseId")
                        .HasPrincipalKey("DiscogScrobblerMVC.Data.Entities.Release", "DiscogsReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.DiscogsReleaseToUser", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Release", "Release")
                        .WithMany("UserAssociations")
                        .HasForeignKey("DiscogsReleaseId")
                        .HasPrincipalKey("DiscogsReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.ReleaseGenre", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Genre", "Genre")
                        .WithMany("ReleaseLinks")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Release", "Release")
                        .WithMany("GenreLinks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.ReleaseStyle", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Release", "Release")
                        .WithMany("StyleLinks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Style", "Style")
                        .WithMany("ReleaseLinks")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Track", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Release", "Release")
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("LabelRelease", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscogScrobblerMVC.Data.Entities.Release", null)
                        .WithMany()
                        .HasForeignKey("ReleasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscogScrobblerMVC.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DiscogScrobblerMVC.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Genre", b =>
                {
                    b.Navigation("ReleaseLinks");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Release", b =>
                {
                    b.Navigation("GenreLinks");

                    b.Navigation("Images");

                    b.Navigation("StyleLinks");

                    b.Navigation("Tracks");

                    b.Navigation("UserAssociations");
                });

            modelBuilder.Entity("DiscogScrobblerMVC.Data.Entities.Style", b =>
                {
                    b.Navigation("ReleaseLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
